### ISSUE TITLE
Relationship with `react-native-web-webrtc`?

### ISSUE THREAD

**Issue by piranna** [react-native-webrtc/react-native-webrtc-web-shim#2]
How does this project relates to [react-native-web-webrtc](https://github.com/liivevideo/react-native-web-webrtc)? Does it replaces it? Maybe can we merge both projects and get the npm package name?

**Comment by fukemy** [comment]
hi, it's important question i think so, please answer this

**Comment by 8BallBomBom** [comment]
Late response but for future reference.
There is no direct relation as such.

The linked module is a shim similar to this module but just links WebRTC functions with the equivalent running environments built in functions instead of something like `react-native-webrtc`.
