### ISSUE TITLE
install issue 

### ISSUE THREAD

**Issue by bmatusiak** [react-native-webrtc/react-native-webrtc-web-shim#7]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: my-app@1.0.0
npm ERR! Found: react-native-webrtc@111.0.6
npm ERR! node_modules/react-native-webrtc
npm ERR!   react-native-webrtc@"^111.0.6" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-native-webrtc@"~1" from react-native-webrtc-web-shim@1.0.4
npm ERR! node_modules/react-native-webrtc-web-shim
npm ERR!   react-native-webrtc-web-shim@"https://github.com/react-native-webrtc/react-native-webrtc-web-shim" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /home/bmatusiak/.npm/_logs/2023-11-01T01_01_24_996Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /home/bmatusiak/.npm/_logs/2023-11-01T01_01_24_996Z-debug-0.log

**Comment by 8BallBomBom** [comment]
Alrighty, very unusual, will check on a few things 🤔
